version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/packages/eslint-config"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
    commit_message:
      prefix: "misc"
    default_labels:
      - "Action: no bump"
      - "packages/eslint-config"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "in_range"

  - package_manager: "javascript"
    directory: "/packages/eslint-config-jest"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
    commit_message:
      prefix: "misc"
    default_labels:
      - "Action: no bump"
      - "packages/eslint-config-jest"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "in_range"

  - package_manager: "javascript"
    directory: "/packages/eslint-config-mocha"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
    commit_message:
      prefix: "misc"
    default_labels:
      - "Action: no bump"
      - "packages/eslint-config-mocha"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "in_range"

  - package_manager: "javascript"
    directory: "/packages/eslint-config-redux-saga"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
    commit_message:
      prefix: "misc"
    default_labels:
      - "Action: no bump"
      - "packages/eslint-config-redux-saga"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "in_range"

  - package_manager: "javascript"
    directory: "/packages/eslint-config-storybook"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
    commit_message:
      prefix: "misc"
    default_labels:
      - "Action: no bump"
      - "packages/eslint-config-storybook"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "in_range"
